---
- name: Manage Firewall
  hosts: demo-aap-checkpoint-smartcenter-api
  gather_facts: False

  vars:
    project_code_name: flow-fusion
    project_state: present
    db_host_ip: "192.168.150.10"
    db_host_netmask: "255.255.255.0"

  vars_files: 
    - "host_vars/demo-aap-checkpoint-smartcenter-api.yml"

  tasks:
    - name: Create/Update/Delete Check Point host objects
      check_point.mgmt.cp_mgmt_host:
        auto_publish_session: True
        name: "{{ project_code_name }}-db"
        ipv4_address: "{{ db_host_ip }}"
        nat_settings: {}
        color: "forest green"
        comments: "Project {{ project_code_name }}"
        groups: []

        state: "{{ project_state }}"