---
- name: Manage Firewall
  hosts: localhost

  vars:
    project_code_name: flow-fusion
    project_state: present
    db_host_ip: "192.168.150.10"
    db_host_netmask: "255.255.255.0"


  tasks:
    - name: Create/Update/Delete Check Point host objects
      check_point.mgmt.cp_mgmt_host:
        auto_publish_session: True
        name: "{{ project_code_name }}-db"
        ipv4_address: "{{ db_host_ip }}"
        nat_settings:
          auto_rule' : 'no'
        color: "forestgreen"
        comments: "{{ ansible_managed }} - {{ project_code_name }}"
        groups: []

        state: "{{ project_state }}"