---
- name: Manage Firewall
  hosts: smartcenter-api
  gather_facts: False

  vars:
    project_code_name: flow-fusion
    project_state: present
    db_host_ip: "192.168.150.10"
    db_host_snat_ip: "172.27.55.221"
    db_host_netmask: "255.255.255.0"
    install_access_policy: true

  tasks:

    - name: Get Check Point version
      check_point.mgmt.cp_mgmt_show_api_versions:
      register: ckp_api_version_information

    - name: Get host object details if project is absent
      cp_mgmt_host_facts:
        name: "{{ project_code_name }}-db"
      register: obj_data

    - name: debug
      debug:
        var: obj_data

    - name: Create/Update/Delete Check Point host object for Database
      check_point.mgmt.cp_mgmt_host:
        name: "{{ project_code_name }}-db"
        ipv4_address: "{{ db_host_ip }}"
        nat_settings:
          auto_rule: True
          ip_address: "{{ db_host_snat_ip }}"
          method: static
        color: "forest green"
        comments: "Project {{ project_code_name }}"
        groups: []
        ignore_errors: true
        ignore_warnings: true
        state: "{{ project_state }}"
      notify: 
        - Publish Changes
        - Install Access Policy

    - name: Create a new rule section for the project's rules
      check_point.mgmt.cp_mgmt_access_section:
        name: "{{ project_code_name }} Rules"
        layer: "Network"
        relative_position:
          below: "Automation Rules"
        state: "{{ project_state }}"
      notify: 
        - Publish Changes
        - Install Access Policy

    - name: add-access-rule for ssh
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Network
        name: Allow SSH Access for Admins
        relative_position:
          below: "{{ project_code_name }} Rules"
        enabled: true
        action: Accept
        track:
          type: Log
        source:
          - "n.internal.192.168.206.1-24"
        destination:
          - "{{ project_code_name }}-db"
        service:
          - ssh_version_2
        comments: "This rule is managed by Ansible"
        vpn: Any
        state: "{{ project_state }}"
      notify: 
        - Publish Changes
        - Install Access Policy

    - name: add-access-rule for mysql
      check_point.mgmt.cp_mgmt_access_rule:
        layer: Network
        name: Allow MySQL Access for Frontend
        relative_position:
          below: "{{ project_code_name }} Rules"
        enabled: true
        action: Accept
        track:
          type: Log
        source:
          - "Any"
        destination:
          - "{{ project_code_name }}-db"
        service:
          - MySQL
        comments: "This rule is managed by Ansible"
        vpn: Any
        state: "{{ project_state }}"
      notify: 
        - Publish Changes
        - Install Access Policy

  handlers:

    - name: Publish Changes
      check_point.mgmt.cp_mgmt_publish:

    - name: Install Access Policy
      check_point.mgmt.cp_mgmt_install_policy:
        access: true
        policy_package: Standard
      when: install_access_policy is true