---
- name: Manage Firewall
  hosts: smartcenter-api
  gather_facts: False

  vars:
    project_code_name: flow-fusion
    project_state: present
    db_host_ip: "192.168.150.10"
    db_host_snat_ip: "172.27.55.221"
    db_host_netmask: "255.255.255.0"

  tasks:

    - name: Get Check Point version
      check_point.mgmt.cp_mgmt_show_api_versions:

    - name: Create/Update/Delete Check Point host object for Database
      check_point.mgmt.cp_mgmt_host:
        auto_publish_session: True
        name: "{{ project_code_name }}-db"
        ipv4_address: "{{ db_host_ip }}"
        nat_settings:
          auto_rule: True
          ip_address: "{{ db_host_snat_ip }}"
          method: static
        color: "forest green"
        comments: "Project {{ project_code_name }}"
        groups: []

        state: "{{ project_state }}"

  handlers:

    - name: Publish Changes
      check_point.mgmt.cp_mgmt_publish: